// Phase 5 schema modularization: domain barrel over legacy exports
export {
  securityAuditLog,
  incidents,
  oncallRotation,
  supportTickets,
  moderationEvents,
  awardHistory,
  imageUploads,
  featuredVideoSlots,
  incidentsRelations,
  oncallRotationRelations,
  securityAuditLogRelations,
  supportTicketsRelations,
  moderationEventsRelations,
  insertSupportTicketSchema,
  insertModerationEventSchema,
  insertAwardHistorySchema,
  insertImageUploadSchema,
  insertFeaturedVideoSlotSchema,
  requestLogs,
  requestLogsRelations,
  adminDailyReports,
} from "./legacy";

export type {
  InsertSupportTicket,
  SupportTicket,
  InsertModerationEvent,
  ModerationEvent,
  AwardHistory,
  InsertAwardHistory,
  ImageUpload,
  InsertImageUpload,
  FeaturedVideoSlot,
  InsertFeaturedVideoSlot,
  RequestLog,
  InsertRequestLog,
  AdminDailyReport,
  InsertAdminDailyReport,
} from "./legacy";
