// Phase 5 schema modularization: domain barrel over legacy exports
export {
  deals,
  dealClaims,
  reviews,
  verificationRequests,
  dealViews,
  dealFeedback,
  dealsRelations,
  dealClaimsRelations,
  reviewsRelations,
  verificationRequestsRelations,
  dealViewsRelations,
  dealFeedbackRelations,
  insertDealSchema,
  insertDealClaimSchema,
  insertDealViewSchema,
  insertReviewSchema,
  insertVerificationRequestSchema,
  insertDealFeedbackSchema,
  lisaClaims,
  LISA_CLAIM_TYPES,
  LISA_CLAIM_SOURCES,
  claims,
  CLAIM_TYPES,
  CLAIM_STATUS,
} from "./legacy";

export type {
  InsertDeal,
  Deal,
  InsertDealClaim,
  DealClaim,
  InsertReview,
  Review,
  InsertVerificationRequest,
  VerificationRequest,
  InsertDealView,
  DealView,
  InsertDealFeedback,
  DealFeedback,
  LisaClaim,
  LisaClaimType,
  LisaClaimSource,
  Claim,
  InsertClaim,
  ClaimType,
  ClaimStatus,
} from "./legacy";
