// Phase 5 schema modularization: domain barrel over legacy exports
export {
  events,
  eventInterests,
  eventBookings,
  eventParticipationMutations,
  eventParticipationMutationChildren,
  eventSeriesPublicationOperations,
  eventSeriesPublicationChildren,
  eventNotificationDeliveries,
  eventInterestsRelations,
  eventsRelations,
  eventBookingsRelations,
  insertEventSchema,
  insertEventInterestSchema,
  insertEventBookingSchema,
  telemetryEvents,
} from "./legacy";

export type {
  Event,
  InsertEvent,
  EventInterest,
  InsertEventInterest,
  EventBooking,
  InsertEventBooking,
  EventParticipationMutation,
  InsertEventParticipationMutation,
  EventParticipationMutationChild,
  InsertEventParticipationMutationChild,
  EventSeriesPublicationOperation,
  InsertEventSeriesPublicationOperation,
  EventSeriesPublicationChild,
  InsertEventSeriesPublicationChild,
  EventNotificationDelivery,
  InsertEventNotificationDelivery,
  TelemetryEvent,
  InsertTelemetryEvent,
} from "./legacy";
