// Phase 5 schema modularization: domain barrel over legacy exports
export {
  hostLocationClaims,
  hosts,
  eventSeries,
  hostReviews,
  hostEarningsLedger,
  hostPayoutRequests,
  hostLocationClaimsRelations,
  hostsRelations,
  hostReviewsRelations,
  insertHostLocationClaimSchema,
  insertHostSchema,
  insertEventSeriesSchema,
  insertHostReviewSchema,
  hostPartnerLeads,
  hostPartnerLeadSequenceSends,
  insertHostPartnerLeadSchema,
} from "./legacy";

export type {
  InsertHostPartnerLead,
  HostLocationClaim,
  InsertHostLocationClaim,
  HostEarningsLedger,
  InsertHostEarningsLedger,
  HostPayoutRequest,
  InsertHostPayoutRequest,
  InsertUserPayoutPreferences,
  Host,
  InsertHost,
  EventSeries,
  InsertEventSeries,
  HostReview,
  InsertHostReview,
  HostPartnerLead,
  InsertHostPartnerLeadRow,
  HostPartnerLeadSequenceSend,
  InsertHostPartnerLeadSequenceSend,
} from "./legacy";
