// Phase 5 schema modularization: domain barrel over legacy exports
export {
  menus,
  menuCategories,
  menuItems,
  menuItemVariants,
  menuItemModifiers,
  menuImportLogs,
  pickupOrders,
  pickupOrderItems,
  orderNotifications,
  menusRelations,
  menuCategoriesRelations,
  menuItemsRelations,
  menuItemVariantsRelations,
  menuItemModifiersRelations,
  pickupOrdersRelations,
  pickupOrderItemsRelations,
  orderNotificationsRelations,
  insertMenuSchema,
  insertMenuCategorySchema,
  insertMenuItemSchema,
  insertMenuItemVariantSchema,
  insertMenuItemModifierSchema,
  insertPickupOrderSchema,
  insertPickupOrderItemSchema,
} from "./legacy";

export type {
  Menu,
  InsertMenu,
  MenuCategory,
  InsertMenuCategory,
  MenuItem,
  InsertMenuItem,
  MenuItemVariant,
  InsertMenuItemVariant,
  MenuItemModifier,
  InsertMenuItemModifier,
  MenuImportLog,
  PickupOrder,
  InsertPickupOrder,
  PickupOrderItem,
  InsertPickupOrderItem,
  OrderNotification,
} from "./legacy";
