// Phase 5 schema modularization: domain barrel over legacy exports
export {
  parkingPassBlackoutDates,
  truckManualSchedules,
  truckParkingReports,
  parkingPassBlackoutDatesRelations,
  truckManualSchedulesRelations,
  truckParkingReportsRelations,
  insertParkingPassBlackoutDateSchema,
  parkingRoutePlans,
  parkingPassPurchases,
  parkingPassCancellationOperations,
  parkingPassProviderOperations,
  parkingPassProviderOperationSteps,
  parkingPassCreditLedger,
  parkingPassArrivalVersions,
} from "./legacy";

export type {
  ParkingPassBlackoutDate,
  InsertParkingPassBlackoutDate,
  TruckManualSchedule,
  TruckParkingReport,
  ParkingRoutePlan,
  InsertParkingRoutePlan,
  ParkingPassPurchase,
  InsertParkingPassPurchase,
  ParkingPassCancellationOperation,
  InsertParkingPassCancellationOperation,
  ParkingPassProviderOperation,
  InsertParkingPassProviderOperation,
  ParkingPassProviderOperationStep,
  InsertParkingPassProviderOperationStep,
  ParkingPassCreditEntry,
  InsertParkingPassCreditEntry,
  ParkingPassArrivalVersion,
  InsertParkingPassArrivalVersion,
} from "./legacy";
