// Phase 5 schema modularization: domain barrel over legacy exports
export {
  users,
  userAddresses,
  passwordResetTokens,
  phoneVerificationTokens,
  accountSetupTokens,
  apiKeys,
  clientQuotas,
  rateLimitCounters,
  usersRelations,
  apiKeysRelations,
  clientQuotasRelations,
  userReviewerLevels,
  userReviewerLevelsRelations,
  userAddressesRelations,
  passwordResetTokensRelations,
  accountSetupTokensRelations,
  insertUserAddressSchema,
  insertPasswordResetTokenSchema,
  insertPhoneVerificationTokenSchema,
  insertAccountSetupTokenSchema,
  emailVerificationTokens,
  userPayoutPreferences,
  userPayoutPreferencesRelations,
  insertEmailVerificationTokenSchema,
} from "./legacy";

export type {
  UpsertUser,
  User,
  FacebookUserData,
  GoogleUserData,
  TradeScoutUserData,
  EmailUserData,
  InsertUserAddress,
  UserAddress,
  InsertPasswordResetToken,
  PasswordResetToken,
  InsertPhoneVerificationToken,
  PhoneVerificationToken,
  InsertAccountSetupToken,
  AccountSetupToken,
  UserReviewerLevel,
  UserPayoutPreferences,
  EmailVerificationToken,
  InsertEmailVerificationToken,
} from "./legacy";
