import assert from 'node:assert/strict';
import { test } from 'node:test';
import { inspectParkingProvider } from '../parkingProviderReadiness.mjs';
const source='a'.repeat(40),live='sk_live_fixture_not_a_credential',sandbox='sk_test_fixture_not_a_credential';
function setup(overrides={}){
 const calls=[];let saved=null;
 const fetchImpl=async(url,options)=>{calls.push({op:'GET',url,key:options.headers.Authorization,method:options.method});assert.equal(options.method,'GET');return{ok:true,status:200,json:async()=>url.endsWith('/v1/account')?{id:'acct_fixture',charges_enabled:true,payouts_enabled:true}:{has_more:false,data:[{url:'https://www.mealscout.us/api/stripe/webhook',status:'enabled',enabled_events:['payment_intent.succeeded']}]}};};
 const createProvider=key=>{calls.push({op:'factory',key});assert.equal(key,sandbox);return{paymentIntents:{
  create:async(data,options)=>{calls.push({op:'create',data,options});saved??={...data,id:'pi_fixture',livemode:false,status:'requires_payment_method',amount_received:0,amount_capturable:0};return structuredClone(saved);},
  retrieve:async id=>{calls.push({op:'retrieve',id});return structuredClone(saved);},
  cancel:async(id,data,options)=>{calls.push({op:'cancel',id,data,options});saved.status='canceled';return structuredClone(saved);},
 }};};
 return{calls,args:{environment:{RENDER_GIT_COMMIT:source,STRIPE_SECRET_KEY:live,STRIPE_WEBHOOK_SECRET:'whsec_fixture',...overrides},fetchImpl,createProvider,nonce:'fixture'}};
}
test('live credentials perform GET only and never fall back to synthetic writes',async()=>{const {calls,args}=setup();const result=await inspectParkingProvider(args);assert.equal(result.result,'partial');assert.equal(result.primary.authenticated,true);assert.equal(result.sandbox.result,'not_run');assert.equal(result.liveMutationCalls,0);assert.equal(result.customerPaymentAcceptance,false);assert.equal(calls.length,2);assert.ok(calls.every(c=>c.method==='GET'));assert.ok(!JSON.stringify(result).includes(live));});
test('sandbox creates one unconfirmed intent with an identical-key replay and cancels it',async()=>{const {calls,args}=setup({STRIPE_SECRET_KEY:sandbox});const result=await inspectParkingProvider(args);assert.equal(result.result,'pass');assert.equal(result.sandbox.sameIntentOnReplay,true);assert.equal(result.sandbox.distinctIntentIds,1);assert.equal(result.sandbox.amountReceived,0);assert.equal(result.sandbox.finalStatus,'canceled');const creates=calls.filter(c=>c.op==='create');assert.equal(creates.length,2);assert.deepEqual(creates[0].data,creates[1].data);assert.deepEqual(creates[0].options,creates[1].options);assert.equal(creates[0].data.confirm,undefined);assert.equal(creates[0].data.payment_method,undefined);assert.equal(calls.filter(c=>c.op==='cancel').length,1);assert.ok(!JSON.stringify(result).includes(sandbox));});
test('primary live key and explicit sandbox key remain separated',async()=>{const {calls,args}=setup({STRIPE_TEST_SECRET_KEY:sandbox});const result=await inspectParkingProvider(args);assert.equal(result.result,'pass');assert.ok(calls.filter(c=>c.op==='GET').every(c=>c.key==='Bearer '+live));assert.ok(calls.filter(c=>c.op==='factory').every(c=>c.key===sandbox));assert.equal(result.webhookConfiguration.remoteDeliveryProven,false);});
test('missing credentials are unavailable, not an acceptance pass',async()=>{const {calls,args}=setup({STRIPE_SECRET_KEY:''});const result=await inspectParkingProvider(args);assert.equal(result.result,'unavailable');assert.equal(result.primary.reason,'not_configured');assert.equal(calls.length,0);});
test('failed live authentication is reported without logging the secret',async()=>{const {args}=setup();args.fetchImpl=async()=>({ok:false,status:401});const result=await inspectParkingProvider(args);assert.equal(result.result,'unavailable');assert.equal(result.primary.httpStatus,401);assert.ok(!JSON.stringify(result).includes(live));});
test('a live-mode response from a sandbox factory cannot be cancelled or confirmed',async()=>{const {args}=setup({STRIPE_TEST_SECRET_KEY:sandbox});let cancel=0;args.createProvider=()=>({paymentIntents:{create:async()=>({id:'pi_unexpected',livemode:true}),retrieve:async()=>({id:'pi_unexpected',livemode:true,status:'requires_payment_method'}),cancel:async()=>{cancel++;}}});const result=await inspectParkingProvider(args);assert.equal(result.sandbox.result,'fail');assert.equal(cancel,0);assert.equal(result.customerPaymentAcceptance,false);});
test('disabled configured webhook is not remote-delivery or acceptance proof',async()=>{const {args}=setup({STRIPE_TEST_SECRET_KEY:sandbox});const previous=args.fetchImpl;args.fetchImpl=async(url,options)=>url.includes('webhook_endpoints')?{ok:true,status:200,json:async()=>({has_more:false,data:[{url:'https://www.mealscout.us/api/stripe/webhook',status:'disabled',enabled_events:['*']}]})}:previous(url,options);const result=await inspectParkingProvider(args);assert.equal(result.result,'partial');assert.equal(result.webhookConfiguration.paymentSuccessConfigured,false);});
test('a live key placed in the sandbox variable is never used for writes',async()=>{const {calls,args}=setup({STRIPE_TEST_SECRET_KEY:live});const result=await inspectParkingProvider(args);assert.equal(result.sandbox.result,'not_run');assert.ok(calls.every(c=>c.op==='GET'));});
