// Actual expiry service + Drizzle + PGlite, with model-derived columns and migration142.
// Synthetic provider only. No real Stripe calls, credentials or public bookings.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import Module from 'node:module';
import { build } from 'esbuild';
import { PGlite } from '@electric-sql/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import { is, SQL, eq } from 'drizzle-orm';
import { getTableConfig, PgDialect } from 'drizzle-orm/pg-core';
const root=process.cwd();
for(const key of Object.keys(process.env)) assert.ok(!/DATABASE_URL|STRIPE.*KEY|BREVO.*KEY/.test(key),'Provider credentials forbidden');
const pg=new PGlite(), database=drizzle(pg), dialect=new PgDialect();
let beforeTransaction=async()=>{};
globalThis.__expiryDb=new Proxy(database,{get(target,key){if(key==='transaction')return async fn=>{await beforeTransaction();return target.transaction(fn);};const value=target[key];return typeof value==='function'?value.bind(target):value;}});
const bundle=await build({stdin:{contents:'export {expireParkingPassHolds} from "./server/services/parkingHoldExpiry"; export {eventBookings} from "./shared/schema";',resolveDir:root,loader:'ts'},bundle:true,platform:'node',format:'cjs',packages:'external',write:false,alias:{'@shared':path.join(root,'shared')},plugins:[{name:'isolated-db',setup(b){b.onResolve({filter:/\/db$/},a=>a.path==='../db'?{path:'db',namespace:'qa'}:undefined);b.onLoad({filter:/.*/,namespace:'qa'},()=>({contents:'export const db=globalThis.__expiryDb;',loader:'js'}));}}]});
const module=new Module(path.join(root,'scripts/qa/.hold-expiry.cjs'));module.filename=path.join(root,'scripts/qa/.hold-expiry.cjs');module.paths=Module._nodeModulePaths(root);module._compile(bundle.outputFiles[0].text,module.filename);
const {expireParkingPassHolds:expire,eventBookings:table}=module.exports;
const quote=s=>'"'+s.replaceAll('"','""')+'"';
const config=getTableConfig(table);
const defs=config.columns.map(c=>{let d=quote(c.name)+' '+c.getSQLType();if(c.primary)d+=' PRIMARY KEY';if(c.notNull)d+=' NOT NULL';if(c.default!==undefined)d+=' DEFAULT '+(is(c.default,SQL)?dialect.sqlToQuery(c.default).sql:typeof c.default==='string'?"'"+c.default.replaceAll("'","''")+"'":String(c.default));return d;});
await pg.exec('CREATE TABLE event_bookings('+defs.join(',')+',CONSTRAINT uq_bookings_event_truck UNIQUE(event_id,truck_id))');
const migration=fs.readFileSync(path.join(root,'migrations/142_parking_pass_active_booking_uniqueness.sql'),'utf8');await pg.exec(migration);
const now=new Date('2026-09-17T00:00:00Z'), cutoff=new Date(now.getTime()-7*60000);
const options={now,ttlMs:7*60000};
let calls=[],intent,cancelImpl,retrieveImpl;
const resultRows=()=>database.select().from(table);
const provider={retrieve:async id=>{calls.push({method:'retrieve',id});return retrieveImpl(id);},cancel:async(id,params,request)=>{calls.push({method:'cancel',id,params,request});return cancelImpl(id);}};
async function seed(extra={}){const id=extra.id||'qa-hold';await database.insert(table).values({id,eventId:extra.eventId||'qa-event',truckId:'qa-truck',hostId:'qa-host',hostPriceCents:1500,platformFeeCents:1000,totalCents:2500,status:'pending',stripePaymentIntentId:'pi_qa_expiry',stripePaymentStatus:'pending',createdAt:new Date(now.getTime()-20*60000),...extra});return id;}
function resetProvider(){calls=[];intent={id:'pi_qa_expiry',status:'requires_payment_method',amount:2500,currency:'usd',amount_received:0,amount_capturable:0,metadata:{truckId:'qa-truck',hostId:'qa-host',totalCents:'2500'}};retrieveImpl=async()=>structuredClone(intent);cancelImpl=async()=>{intent.status='canceled';return structuredClone(intent);};beforeTransaction=async()=>{};}
const results=[];
async function test(name,fn){await pg.exec('TRUNCATE event_bookings');resetProvider();try{await fn();results.push({name,status:'pass'});}catch(error){results.push({name,status:'fail',error:error.message});}console.log('QA EXPIRY '+JSON.stringify(results.at(-1)));}
const noCancel=()=>assert.equal(calls.filter(c=>c.method==='cancel').length,0);
try{
await test('expired unpaid hold is marked cancelled without deleting its evidence',async()=>{await seed();const r=await expire(provider,options);assert.equal(r.expired,1);const [row]=await resultRows();assert.equal(row.id,'qa-hold');assert.equal(row.status,'cancelled');assert.equal(row.stripePaymentIntentId,intent.id);assert.equal(row.cancellationReason,'checkout_hold_expired');assert.equal(calls.filter(c=>c.method==='cancel').length,1);});
for(const status of ['requires_confirmation','requires_action'])await test('unpaid '+status+' expires after confirmed provider cancellation',async()=>{await seed();intent.status=status;assert.equal((await expire(provider,options)).expired,1);});
await test('already cancelled unpaid intent releases holds without another cancellation',async()=>{await seed();intent.status='canceled';assert.equal((await expire(provider,options)).expired,1);noCancel();});
for(const status of ['succeeded','processing','requires_capture','unknown'])await test('provider '+status+' retains pending evidence and capacity',async()=>{await seed();intent.status=status;assert.equal((await expire(provider,options)).expired,0);assert.equal((await resultRows())[0].status,'pending');noCancel();});
for(const field of ['amount_received','amount_capturable'])await test('nonzero '+field+' prevents automatic cancellation',async()=>{await seed();intent[field]=10;assert.equal((await expire(provider,options)).expired,0);noCancel();});
await test('absent provider amounts are not treated as zero',async()=>{await seed();delete intent.amount_received;assert.equal((await expire(provider,options)).expired,0);noCancel();});
await test('missing payment link is retained without guessing a provider ID',async()=>{await seed({stripePaymentIntentId:null});assert.equal((await expire(provider,options)).scanned,0);assert.equal((await resultRows()).length,1);assert.equal(calls.length,0);});
await test('missing Stripe configuration cannot delete holds',async()=>{await seed();assert.equal((await expire(null,options)).expired,0);assert.equal((await resultRows())[0].status,'pending');});
await test('fresh and exact-deadline holds are not expired',async()=>{await seed({createdAt:cutoff});assert.equal((await expire(provider,options)).scanned,0);assert.equal(calls.length,0);});
await test('one fresh row protects the whole multi-day payment',async()=>{await seed();await seed({id:'qa-fresh',eventId:'qa-day2',createdAt:now});assert.equal((await expire(provider,options)).expired,0);assert.equal(calls.length,0);});
await test('a confirmed sibling protects the whole payment',async()=>{await seed();await seed({id:'qa-confirmed',eventId:'qa-day2',status:'confirmed'});assert.equal((await expire(provider,options)).expired,0);assert.equal(calls.length,0);});
for(const field of ['paidAt','bookingConfirmedAt'])await test(field+' prevents expiry even if status is stale',async()=>{await seed({[field]:now});assert.equal((await expire(provider,options)).expired,0);assert.equal(calls.length,0);});
await test('stored processing payment cannot be cancelled by a stale provider read',async()=>{await seed({stripePaymentStatus:'processing'});assert.equal((await expire(provider,options)).expired,0);assert.equal(calls.length,0);});
for(const [field,value] of [['id','pi_other'],['currency','eur'],['amount',2501]])await test('mismatched provider '+field+' stays untouched',async()=>{await seed();intent[field]=value;assert.equal((await expire(provider,options)).expired,0);noCancel();});
for(const field of ['truckId','hostId','totalCents'])await test('mismatched '+field+' metadata blocks cancellation',async()=>{await seed();intent.metadata[field]='other';assert.equal((await expire(provider,options)).expired,0);noCancel();});
await test('provider lookup failure retains the original hold',async()=>{await seed();retrieveImpl=async()=>{throw new Error('QA offline');};assert.equal((await expire(provider,options)).errors,1);assert.equal((await resultRows())[0].status,'pending');noCancel();});
await test('lost cancellation acknowledgement recovers only a positive cancelled result',async()=>{await seed();cancelImpl=async()=>{intent.status='canceled';throw new Error('QA lost ack');};assert.equal((await expire(provider,options)).expired,1);assert.equal(calls.filter(c=>c.method==='retrieve').length,2);});
await test('cancellation race with successful payment preserves the hold',async()=>{await seed();cancelImpl=async()=>{intent.status='succeeded';intent.amount_received=2500;throw new Error('QA already paid');};assert.equal((await expire(provider,options)).expired,0);assert.equal((await resultRows())[0].status,'pending');});
await test('failed cancellation and failed status reread never release capacity',async()=>{await seed();let n=0;retrieveImpl=async()=>{if(n++)throw new Error('QA offline');return structuredClone(intent);};cancelImpl=async()=>{throw new Error('QA cancel failure');};assert.equal((await expire(provider,options)).errors,1);assert.equal((await resultRows())[0].status,'pending');});
await test('misidentified cancellation response cannot mutate booking rows',async()=>{await seed();cancelImpl=async()=>({...intent,id:'pi_other',status:'canceled'});assert.equal((await expire(provider,options)).expired,0);assert.equal((await resultRows())[0].status,'pending');});
await test('all expired multi-day holds release together after one verified cancellation',async()=>{await seed();await seed({id:'qa-day2',eventId:'qa-day2'});intent.amount=5000;intent.metadata.totalCents='5000';assert.equal((await expire(provider,options)).expired,2);assert.ok((await resultRows()).every(r=>r.status==='cancelled'));assert.equal(calls.filter(c=>c.method==='cancel').length,1);});
await test('status changed after candidate selection is rechecked under lock',async()=>{await seed();beforeTransaction=async()=>{await database.update(table).set({status:'confirmed'}).where(eq(table.id,'qa-hold'));beforeTransaction=async()=>{};};assert.equal((await expire(provider,options)).expired,0);assert.equal((await resultRows())[0].status,'confirmed');noCancel();});
await test('two sweep invocations cannot cancel the same payment twice',async()=>{await seed();const results=await Promise.all([expire(provider,options),expire(provider,options)]);assert.equal(results.reduce((n,r)=>n+r.expired,0),1);assert.equal(calls.filter(c=>c.method==='cancel').length,1);});
await test('failed database acknowledgement leaves evidence recoverable on the next sweep',async()=>{await seed();await pg.exec("CREATE FUNCTION qa_expiry_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'QA write failure'; END $$; CREATE TRIGGER qa_expiry_fail BEFORE UPDATE ON event_bookings FOR EACH ROW EXECUTE FUNCTION qa_expiry_fail()");try{assert.equal((await expire(provider,options)).errors,1);assert.equal((await resultRows())[0].status,'pending');assert.equal(intent.status,'canceled');}finally{await pg.exec('DROP TRIGGER qa_expiry_fail ON event_bookings; DROP FUNCTION qa_expiry_fail()');}assert.equal((await expire(provider,options)).expired,1);assert.equal(calls.filter(c=>c.method==='cancel').length,1);});
await test('expired history does not block rebooking but active duplicates remain forbidden',async()=>{await seed();await expire(provider,options);await seed({id:'qa-new',createdAt:now,stripePaymentIntentId:'pi_qa_new'});await assert.rejects(seed({id:'qa-duplicate'}));const rows=await resultRows();assert.equal(rows.length,2);assert.equal(rows.filter(r=>r.status==='pending').length,1);assert.equal(rows.filter(r=>r.status==='cancelled').length,1);});
await test('migration is rerunnable and preserves confirmed booking uniqueness',async()=>{await pg.exec(migration);await seed({status:'confirmed'});await assert.rejects(seed({id:'qa-conflict'}));assert.equal((await resultRows()).length,1);});
await test('cursor advances past unresolved holds instead of starving later work',async()=>{await seed({id:'qa-a',stripePaymentIntentId:'pi_a'});await seed({id:'qa-z',eventId:'qa-z',stripePaymentIntentId:'pi_z'});retrieveImpl=async id=>({...intent,id,status:id==='pi_a'?'processing':'canceled'});const first=await expire(provider,{...options,limit:1});assert.equal(first.nextCursor,'pi_a');assert.equal(first.expired,0);const second=await expire(provider,{...options,limit:1,afterIntentId:first.nextCursor});assert.equal(second.expired,1);assert.equal(second.nextCursor,'pi_z');assert.equal((await expire(provider,{...options,afterIntentId:'pi_z'})).nextCursor,null);});
await test('stable cancellation request identity contains no personal fields',async()=>{await seed();await expire(provider,options);const call=calls.find(c=>c.method==='cancel');assert.match(call.request.idempotencyKey,/^parking-pass-expiry:[a-f0-9]{64}$/);assert.deepEqual(call.params,{cancellation_reason:'abandoned'});});
await test('invalid deadline rejects without contacting providers',async()=>{await seed();await assert.rejects(expire(provider,{...options,ttlMs:NaN}));assert.equal(calls.length,0);});
await test('scheduler calls only the safe expiry service and retains its overlap guard',async()=>{const source=fs.readFileSync(path.join(root,'server/bootstrap/registerSchedulers.ts'),'utf8');const slice=source.slice(source.indexOf('// Sweep verified unpaid holds'),source.indexOf('// IndexNow daily'));assert.ok(slice.includes('expireParkingPassHolds(provider'));assert.ok(slice.includes('if (holdExpiryRunning) return'));assert.ok(slice.includes('holdExpiryCursor = outcome.nextCursor'));assert.ok(!slice.includes('.delete('));assert.ok(!slice.includes('eventBookings as any'));});
}finally{await pg.close();delete globalThis.__expiryDb;}
const summary={scope:'Actual expiry service, Drizzle/PGlite and migration142; synthetic Stripe, not native PostgreSQL or real provider proof',pass:results.filter(r=>r.status==='pass').length,fail:results.filter(r=>r.status==='fail').length,results};
const evidence=process.env.QA_EVIDENCE_DIR;if(evidence){fs.mkdirSync(evidence,{recursive:true});fs.writeFileSync(path.join(evidence,'parking-hold-expiry.json'),JSON.stringify(summary,null,2));}
console.log('QA EXPIRY SUMMARY '+JSON.stringify(summary));if(summary.fail)process.exitCode=1;
