import assert from 'node:assert/strict';
import fs from 'node:fs';
const expected=String(process.env.MEAL_TRAFFIC_DASHBOARD_OBSERVE||'');assert.match(expected,/^[a-f0-9]{40}$/);
const report={expected,startedAt:new Date().toISOString(),result:'fail',customerMutations:0,diagnosticWrites:0,authenticatedOperatorSessionObserved:false,checks:[]};
async function get(path){return fetch('https://www.mealscout.us'+path,{headers:{'user-agent':'mealscout-runtime-proof/traffic-quality-readonly','x-mealscout-qa':'1'},redirect:'error',signal:AbortSignal.timeout(20000)});}
async function version(){const response=await get('/api/version');const body=await response.json();const value={status:response.status,commit:body.version?.commit,platform:body.version?.platform};assert.equal(value.status,200);assert.equal(value.commit,expected);return value;}
try{report.before=await version();const response=await get('/api/admin/discovery-observatory/traffic-quality?hours=24');const body=await response.json();assert([401,403].includes(response.status));assert(!Object.hasOwn(body,'report'));assert(!Object.hasOwn(body,'entryEvents'));report.checks.push({name:'anonymous-quality-report-denied',status:response.status,reportExposed:false});report.after=await version();report.result='pass';}
catch(error){report.error=String(error.stack||error);process.exitCode=1;}
finally{report.finishedAt=new Date().toISOString();report.boundary='Live production revision and anonymous report denial only. Authenticated operator functionality was tested with isolated fixtures; no live administrator session or growth is claimed.';const out='test-results/recovery-isolated-report';fs.mkdirSync(out,{recursive:true});fs.writeFileSync(out+'/traffic-dashboard-live.json',JSON.stringify(report,null,2));fs.writeFileSync(out+'/index.html','<meta name="robots" content="noindex,nofollow"><h1>Traffic-quality dashboard release</h1><a href="traffic-dashboard-live.json">GET-only verification</a>');fs.writeFileSync(out+'/robots.txt','User-agent: *\nDisallow: /\n');console.log('MEAL_DASHBOARD_LIVE '+JSON.stringify(report));}
